version: '3'
services:
  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8080:80"
    volumes:
      - ./nagios/etc:/opt/nagios/etc
      - ./nagios/var:/opt/nagios/var
      - ./custom-plugins:/opt/Custom-Nagios-Plugins
    environment:
      - NAGIOSADMIN_PASSWORD=nagiosadmin
  
  target-host:
    image: ubuntu:latest
    command: tail -f /dev/null

networks:
  default:
    driver: bridge
